Release sprint12
* Update .travis.yml

* Revert molecule to its last v1 version.

* Syntax checking (#132)

* EOF

* Molecule is too expensive for syntax check.

* Molecule is too expensive for syntax check.

* Added requirements.txt, removed docker from travis.

* Deleted molecule.yml

* Feature sprint12 update aws sync anna (#134)

* add argument to sync. This will also sync files of the exact same size, but different date

* check synchronization EFS->S3 before deleting files

* Add logging s3 sync commando

* fix typo

* Feature sprint12 update aws sync anna (#135)

* add argument to sync. This will also sync files of the exact same size, but different date

* check synchronization EFS->S3 before deleting files

* Add logging s3 sync commando

* fix typo

* write logs from sync_cleanup container to file

* fix inconsistencies in counting objects on EFS and S3

* fix comparisons

* Only count number of objects in simulation folder

* Feature sprint12 upgrade psql maarten (#133)

* Upgraded postgresql to 9.6

* Migrate to pgsql9.6

* Django user can add databases.

* add installation python-psycopg2

* Added dev only createdb option to django user.

* CREATEDB privs only on develop.

* Added templates for CELERY_ONCE.

* add restart policy for restart amazon machines (#136)

* don't start celery on the celerybeat server (#137)

* don't start celery on the celerybeat server

* fix typo

* Fixed logrotate logrotating logrotated logs (#138)

diff --git a/roles/worker_sync_cleanup/templates/run.sh.j2 b/roles/worker_sync_cleanup/templates/run.sh.j2
--- a/roles/worker_sync_cleanup/templates/run.sh.j2
+++ b/roles/worker_sync_cleanup/templates/run.sh.j2
@@ -9,14 +9,13 @@ if [ -f /sys/hypervisor/uuid ] && [ $(head -c 3 /sys/hypervisor/uuid) == "ec2" ]
     EC2=1
 fi
 
-
 # Amazon specific code goes here
 if [ "$EC2" == "1" ]
 then
     if [ -z "$uuid" ]
     then
-        echo "Failed to find $uuid on amazon, not sure where to put my files"
-        echo "Make sure you set the uuid"
+        echo "Failed to find $uuid on amazon, not sure where to put my files" >> /data/sync_cleanup.log
+        echo "Make sure you set the uuid" >> /data/sync_cleanup.log
         exit 1
     fi
 
@@ -27,11 +26,43 @@ then
         if [ "$argument" == "cleanup" ]
         then
             # synchronize directory with on s3 (make sure you provision aws command lines (pip install aws-cli))
-            aws s3 sync /data/input/ "s3://{{ bucket }}/data/container/files/$uuid" --quiet
+            aws s3 sync /data/input/ "s3://{{ bucket }}/data/container/files/$uuid" --exact-time
 
-            echo "start cleanup"
-            rm -rf /data/input/*
-            echo "All directories are removed"
+            # Capture sync status
+            SYNC_STATUS=$?
+
+            # caputer number of files in the EFS Simulation directory 
+            I="$(find /data/input/simulation -type f | wc -l)"
+
+            # write tree log of the EFS directory
+            ls -lhR /data/input/ > /data/EFStree.log
+
+            # write tree log of the S3 directory
+            aws s3 ls  "s3://{{ bucket }}/data/container/files/$uuid" --recursive --summarize > /data/S3tree.log
+
+            # write temporary tree log of S3 simulation directory
+            aws s3 ls  "s3://{{ bucket }}/data/container/files/$uuid/simulation" --recursive --summarize > /tmp/S3Simulationtree.log
+
+            # capture number of files in the S3 Simulation directory
+            J="$(grep  "^Total Objects:" /tmp/S3Simulationtree.log | grep -Eo "[0-9]+")"
+
+            if [ "$I" == "$J" ] && [ "$SYNC_STATUS" == "0" ];
+            then
+                echo "start cleanup" >> /data/sync_cleanup.log
+                rm -rf /data/input/*
+                echo "All directories are removed" >> /data/sync_cleanup.log
+            else
+                echo "Didn't clean EFS directories" >> /data/sync_cleanup.log
+                echo "Number of files in EFS directory: $I" >> /data/sync_cleanup.log
+                echo "Number of files in S3 directory: $J" >> /data/sync_cleanup.log
+                echo "SYNC_STATUS: $SYNC_STATUS" >> /data/sync_cleanup.log
+            fi
+
+            # sync logfile
+            aws s3 sync /data/ "s3://{{ bucket }}/data/container/files/$uuid/log" --exact-time --exclude "*" --include "*.log"
+
+            # remove logfile
+            rm -rf /data/*.log
 
         elif [ "$argument" == "rerun" ]
         then
@@ -41,7 +72,7 @@ then
             aws s3 cp "s3://{{ bucket }}/data/container/files/$uuid/" "s3://{{ bucket }}/data/container/files/$uuid/backup/" --exclude "simulation/*" --exclude "backup/*" --recursive
             # synchronize simulation folder from s3 back to the Elastic File System. Exclude ini file, this file is generated in do_docker_create task.
             echo "sync S3 to EFS"
-            aws s3 sync "s3://{{ bucket }}/data/container/files/$uuid/simulation" /data/output/simulation --exclude "input.ini"
+            aws s3 sync "s3://{{ bucket }}/data/container/files/$uuid/simulation" /data/output/simulation --exclude "input.ini" --exact-time
         fi
     done
 fi
